#!/usr/bin/env node

/**
 * Lambda States Comparison Script
 *
 * This script compares the Lambda function files between two deployment states
 * to verify they contain the same files.
 *
 * PURPOSE:
 * - Reads two function files JSON outputs for comparison
 * - Compares file lists for each Lambda function
 * - Reports differences and matches
 * - Provides a summary of comparison results
 *
 * USAGE:
 *   npx tsx scripts/compare-states.ts <first-file.json> <second-file.json>
 *
 * PARAMETERS:
 *   first-file.json  : Path to the first function files JSON (e.g., original deployment)
 *   second-file.json : Path to the second function files JSON (e.g., cdk-booster deployment)
 *
 * EXAMPLES:
 *   npx tsx scripts/compare-states.ts cdk-original-function-files.json cdk-booster-function-files.json
 *   npx tsx scripts/compare-states.ts ./original.json ./booster.json
 *
 * EXPECTED INPUT FILES:
 * JSON files generated by export-state.ts with the structure:
 * {
 *   "functions": [{"functionName": "...", "files": ["..."]}],
 *   "timestamp": "..."
 * }
 *
 * OUTPUT:
 * - Console output showing comparison results for each function
 * - Summary of total matches/mismatches
 * - Exit code 0 if all match, 1 if differences found
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Interface representing the file list for a single Lambda function
 */
interface FunctionFilesList {
  functionName: string;
  files: string[];
}

/**
 * Interface representing the complete results output from export-state.ts
 */
interface FunctionFilesResults {
  functions: FunctionFilesList[];
  timestamp: string;
}

/**
 * Interface representing comparison result for a single function
 */
interface FunctionComparison {
  functionName: string;
  matches: boolean;
  originalFiles: string[];
  boosterFiles: string[];
  onlyInOriginal: string[];
  onlyInBooster: string[];
  commonFiles: string[];
}

/**
 * Interface representing the complete comparison results
 */
interface ComparisonResults {
  totalFunctions: number;
  matchingFunctions: number;
  mismatchingFunctions: number;
  functions: FunctionComparison[];
  overallMatch: boolean;
}

/**
 * Compare two arrays of strings and return differences
 */
function compareArrays(
  arr1: string[],
  arr2: string[],
): {
  onlyInFirst: string[];
  onlyInSecond: string[];
  common: string[];
} {
  const set1 = new Set(arr1);
  const set2 = new Set(arr2);

  const onlyInFirst = arr1.filter((item) => !set2.has(item));
  const onlyInSecond = arr2.filter((item) => !set1.has(item));
  const common = arr1.filter((item) => set2.has(item));

  return { onlyInFirst, onlyInSecond, common };
}

/**
 * Main comparison function
 */
function compareCdkStates(
  firstFilePath: string,
  secondFilePath: string,
): ComparisonResults {
  // Check if both files exist
  if (!fs.existsSync(firstFilePath)) {
    throw new Error(`First file not found: ${firstFilePath}`);
  }

  if (!fs.existsSync(secondFilePath)) {
    throw new Error(`Second file not found: ${secondFilePath}`);
  }

  // Read and parse both files
  const firstData: FunctionFilesResults = JSON.parse(
    fs.readFileSync(firstFilePath, 'utf-8'),
  );
  const secondData: FunctionFilesResults = JSON.parse(
    fs.readFileSync(secondFilePath, 'utf-8'),
  );

  // Create maps for easier lookup
  const firstMap = new Map<string, string[]>();
  const secondMap = new Map<string, string[]>();

  firstData.functions.forEach((func) => {
    firstMap.set(func.functionName, func.files.sort());
  });

  secondData.functions.forEach((func) => {
    secondMap.set(func.functionName, func.files.sort());
  });

  // Get all unique function names
  const allFunctionNames = new Set([...firstMap.keys(), ...secondMap.keys()]);

  const functionComparisons: FunctionComparison[] = [];
  let matchingCount = 0;

  // Compare each function
  for (const functionName of Array.from(allFunctionNames).sort()) {
    const firstFiles = firstMap.get(functionName) || [];
    const secondFiles = secondMap.get(functionName) || [];

    const { onlyInFirst, onlyInSecond, common } = compareArrays(
      firstFiles,
      secondFiles,
    );

    const matches = onlyInFirst.length === 0 && onlyInSecond.length === 0;
    if (matches) {
      matchingCount++;
    }

    functionComparisons.push({
      functionName,
      matches,
      originalFiles: firstFiles,
      boosterFiles: secondFiles,
      onlyInOriginal: onlyInFirst,
      onlyInBooster: onlyInSecond,
      commonFiles: common,
    });
  }

  return {
    totalFunctions: allFunctionNames.size,
    matchingFunctions: matchingCount,
    mismatchingFunctions: allFunctionNames.size - matchingCount,
    functions: functionComparisons,
    overallMatch: matchingCount === allFunctionNames.size,
  };
}

/**
 * Print comparison results to console
 */
function printResults(
  results: ComparisonResults,
  firstFile: string,
  secondFile: string,
): void {
  console.log('\n=== CDK States Comparison Results ===\n');

  console.log(`Comparing:`);
  console.log(`  First:  ${firstFile}`);
  console.log(`  Second: ${secondFile}\n`);

  console.log(`Total functions: ${results.totalFunctions}`);
  console.log(`Matching functions: ${results.matchingFunctions}`);
  console.log(`Mismatching functions: ${results.mismatchingFunctions}`);
  console.log(`Overall match: ${results.overallMatch ? 'YES' : 'NO'}\n`);

  // Print details for each function
  for (const func of results.functions) {
    const status = func.matches ? '✅ MATCH' : '❌ MISMATCH';
    console.log(`${status} ${func.functionName}`);

    if (!func.matches) {
      if (func.onlyInOriginal.length > 0) {
        console.log(
          `  Only in first file (${func.onlyInOriginal.length} files):`,
        );
        func.onlyInOriginal.forEach((file) => console.log(`    - ${file}`));
      }

      if (func.onlyInBooster.length > 0) {
        console.log(
          `  Only in second file (${func.onlyInBooster.length} files):`,
        );
        func.onlyInBooster.forEach((file) => console.log(`    + ${file}`));
      }
    }

    console.log(`  Common files: ${func.commonFiles.length}`);
    console.log(
      `  First total: ${func.originalFiles.length}, Second total: ${func.boosterFiles.length}\n`,
    );
  }

  // Final summary
  if (results.overallMatch) {
    console.log('🎉 All Lambda functions have identical file structures!');
  } else {
    console.log('⚠️  Some Lambda functions have different file structures.');
  }
}

/**
 * Main execution function
 */
async function main() {
  const args = process.argv.slice(2);

  if (args.length !== 2) {
    console.error(
      'Usage: npx tsx compare-states.ts <first-file.json> <second-file.json>',
    );
    console.error('');
    console.error('Examples:');
    console.error(
      '  npx tsx compare-states.ts cdk-original-function-files.json cdk-booster-function-files.json',
    );
    console.error('  npx tsx compare-states.ts ./original.json ./booster.json');
    process.exit(1);
  }

  const [firstFile, secondFile] = args;
  const firstFilePath = path.resolve(firstFile);
  const secondFilePath = path.resolve(secondFile);

  try {
    const results = compareCdkStates(firstFilePath, secondFilePath);
    printResults(results, firstFile, secondFile);

    // Exit with error code if there are mismatches
    process.exit(results.overallMatch ? 0 : 1);
  } catch (error) {
    console.error('Error comparing CDK states:', error);
    process.exit(1);
  }
}

// Execute main function only when script is run directly
if (require.main === module) {
  main().catch(console.error);
}

export { compareCdkStates, ComparisonResults, FunctionComparison };
