/**
 * Lambda States Comparison Script
 *
 * This script compares the Lambda function files between two deployment states
 * to verify they contain the same files.
 *
 * PURPOSE:
 * - Reads two function files JSON outputs for comparison
 * - Compares file lists for each Lambda function
 * - Reports differences and matches
 * - Provides a summary of comparison results
 *
 * USAGE:
 *   npx tsx scripts/compare-states.ts <first-file.json> <second-file.json>
 *
 * PARAMETERS:
 *   first-file.json  : Path to the first function files JSON (e.g., original deployment)
 *   second-file.json : Path to the second function files JSON (e.g., cdk-booster deployment)
 *
 * EXAMPLES:
 *   npx tsx scripts/compare-states.ts cdk-original-function-files.json cdk-booster-function-files.json
 *   npx tsx scripts/compare-states.ts ./original.json ./booster.json
 *
 * EXPECTED INPUT FILES:
 * JSON files generated by export-state.ts with the structure:
 * {
 *   "functions": [{"functionName": "...", "files": ["..."]}],
 *   "timestamp": "..."
 * }
 *
 * OUTPUT:
 * - Console output showing comparison results for each function
 * - Summary of total matches/mismatches
 * - Exit code 0 if all match, 1 if differences found
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Interface representing the execution result for a Lambda function
 */
interface FunctionExecutionResult {
  success: boolean;
  output?: string;
  error?: string;
  statusCode?: number;
  executedPayload?: any;
}

/**
 * Interface representing the file list for a single Lambda function
 */
interface FunctionFilesList {
  functionName: string;
  files: string[];
  execution: FunctionExecutionResult;
}

/**
 * Interface representing the state of an S3 bucket deployed via BucketDeployment
 */
interface BucketState {
  bucketName: string;
  objects: string[];
  markerContent?: string;
}

/**
 * Interface representing the complete results output from export-state.ts
 */
interface FunctionFilesResults {
  functions: FunctionFilesList[];
  buckets?: BucketState[];
  timestamp: string;
}

/**
 * Interface representing comparison result for a single file
 */
interface FileComparison {
  fileName: string;
  status: 'match' | 'only-in-first' | 'only-in-second';
}

/**
 * Interface representing execution comparison result
 */
interface ExecutionComparison {
  matches: boolean;
  firstSuccess: boolean;
  secondSuccess: boolean;
  outputMatches: boolean;
  statusCodeMatches: boolean;
  details: string;
}

/**
 * Interface representing comparison result for a single function
 */
interface FunctionComparison {
  functionName: string;
  matches: boolean;
  filesMatch: boolean;
  executionMatch: boolean;
  originalFiles: string[];
  boosterFiles: string[];
  onlyInOriginal: string[];
  onlyInBooster: string[];
  commonFiles: string[];
  fileDetails: FileComparison[];
  executionComparison: ExecutionComparison;
}

/**
 * Interface representing comparison result for an S3 bucket
 */
interface BucketComparison {
  bucketName: string;
  matches: boolean;
  originalObjects: string[];
  boosterObjects: string[];
  onlyInOriginal: string[];
  onlyInBooster: string[];
  commonObjects: string[];
}

/**
 * Interface representing the complete comparison results
 */
interface ComparisonResults {
  totalFunctions: number;
  matchingFunctions: number;
  mismatchingFunctions: number;
  functions: FunctionComparison[];
  totalBuckets: number;
  matchingBuckets: number;
  mismatchingBuckets: number;
  buckets: BucketComparison[];
  overallMatch: boolean;
}

/**
 * Compare two arrays of strings and return differences with detailed file comparison
 */
function compareArrays(
  arr1: string[],
  arr2: string[],
): {
  onlyInFirst: string[];
  onlyInSecond: string[];
  common: string[];
  fileDetails: FileComparison[];
} {
  const set1 = new Set(arr1);
  const set2 = new Set(arr2);

  const onlyInFirst = arr1.filter((item) => !set2.has(item));
  const onlyInSecond = arr2.filter((item) => !set1.has(item));
  const common = arr1.filter((item) => set2.has(item));

  // Create detailed file comparison
  const fileDetails: FileComparison[] = [];

  // Add files that are in both
  common.forEach((file) => {
    fileDetails.push({ fileName: file, status: 'match' });
  });

  // Add files only in first
  onlyInFirst.forEach((file) => {
    fileDetails.push({ fileName: file, status: 'only-in-first' });
  });

  // Add files only in second
  onlyInSecond.forEach((file) => {
    fileDetails.push({ fileName: file, status: 'only-in-second' });
  });

  // Sort by filename for consistent output
  fileDetails.sort((a, b) => a.fileName.localeCompare(b.fileName));

  return { onlyInFirst, onlyInSecond, common, fileDetails };
}

/**
 * Compare execution results between two functions
 */
function compareExecutionResults(
  first: FunctionExecutionResult,
  second: FunctionExecutionResult,
): ExecutionComparison {
  const outputMatches = first.output === second.output;
  const statusCodeMatches = first.statusCode === second.statusCode;
  const bothSuccessful = first.success && second.success;
  const bothFailed = !first.success && !second.success;

  let matches: boolean;
  let details: string;

  if (bothSuccessful) {
    matches = outputMatches && statusCodeMatches;
    if (matches) {
      details = 'Both executions successful with identical outputs';
    } else {
      details = `Both successful but outputs differ - Output match: ${outputMatches}, Status match: ${statusCodeMatches}`;
    }
  } else if (bothFailed) {
    matches = true; // Both failed, consider as match
    details = `Both executions failed - First: ${first.error}, Second: ${second.error}`;
  } else {
    matches = false;
    details = `Execution success differs - First: ${first.success ? 'success' : 'failed'}, Second: ${second.success ? 'success' : 'failed'}`;
  }

  return {
    matches,
    firstSuccess: first.success,
    secondSuccess: second.success,
    outputMatches,
    statusCodeMatches,
    details,
  };
}

/**
 * Main comparison function
 */
function compareCdkStates(
  firstFilePath: string,
  secondFilePath: string,
): ComparisonResults {
  // Check if both files exist
  if (!fs.existsSync(firstFilePath)) {
    throw new Error(`First file not found: ${firstFilePath}`);
  }

  if (!fs.existsSync(secondFilePath)) {
    throw new Error(`Second file not found: ${secondFilePath}`);
  }

  // Read and parse both files
  const firstData: FunctionFilesResults = JSON.parse(
    fs.readFileSync(firstFilePath, 'utf-8'),
  );
  const secondData: FunctionFilesResults = JSON.parse(
    fs.readFileSync(secondFilePath, 'utf-8'),
  );

  // Create maps for easier lookup
  const firstMap = new Map<string, FunctionFilesList>();
  const secondMap = new Map<string, FunctionFilesList>();

  firstData.functions.forEach((func) => {
    firstMap.set(func.functionName, func);
  });

  secondData.functions.forEach((func) => {
    secondMap.set(func.functionName, func);
  });

  // Get all unique function names
  const allFunctionNames = new Set([...firstMap.keys(), ...secondMap.keys()]);

  const functionComparisons: FunctionComparison[] = [];
  let matchingCount = 0;

  // Compare each function
  for (const functionName of Array.from(allFunctionNames).sort()) {
    const firstFunc = firstMap.get(functionName);
    const secondFunc = secondMap.get(functionName);

    const firstFiles = firstFunc?.files || [];
    const secondFiles = secondFunc?.files || [];

    const { onlyInFirst, onlyInSecond, common, fileDetails } = compareArrays(
      firstFiles,
      secondFiles,
    );

    const filesMatch = onlyInFirst.length === 0 && onlyInSecond.length === 0;

    // Compare execution results
    const firstExecution = firstFunc?.execution || {
      success: false,
      error: 'Function not found',
    };
    const secondExecution = secondFunc?.execution || {
      success: false,
      error: 'Function not found',
    };
    const executionComparison = compareExecutionResults(
      firstExecution,
      secondExecution,
    );

    const overallMatch = filesMatch && executionComparison.matches;

    if (overallMatch) {
      matchingCount++;
    }

    functionComparisons.push({
      functionName,
      matches: overallMatch,
      filesMatch,
      executionMatch: executionComparison.matches,
      originalFiles: firstFiles,
      boosterFiles: secondFiles,
      onlyInOriginal: onlyInFirst,
      onlyInBooster: onlyInSecond,
      commonFiles: common,
      fileDetails,
      executionComparison,
    });
  }

  // Compare S3 buckets
  const firstBucketMap = new Map<string, BucketState>();
  const secondBucketMap = new Map<string, BucketState>();

  (firstData.buckets ?? []).forEach((b) => {
    firstBucketMap.set(b.bucketName, b);
  });
  (secondData.buckets ?? []).forEach((b) => {
    secondBucketMap.set(b.bucketName, b);
  });

  const allBucketNames = new Set([
    ...firstBucketMap.keys(),
    ...secondBucketMap.keys(),
  ]);

  const bucketComparisons: BucketComparison[] = [];
  let matchingBucketCount = 0;

  for (const bucketName of Array.from(allBucketNames).sort()) {
    const firstBucket = firstBucketMap.get(bucketName);
    const secondBucket = secondBucketMap.get(bucketName);

    const firstObjects = firstBucket?.objects ?? [];
    const secondObjects = secondBucket?.objects ?? [];

    const firstSet = new Set(firstObjects);
    const secondSet = new Set(secondObjects);

    const onlyInOriginal = firstObjects.filter((o) => !secondSet.has(o));
    const onlyInBooster = secondObjects.filter((o) => !firstSet.has(o));
    const commonObjects = firstObjects.filter((o) => secondSet.has(o));

    const matches = onlyInOriginal.length === 0 && onlyInBooster.length === 0;
    if (matches) matchingBucketCount++;

    bucketComparisons.push({
      bucketName,
      matches,
      originalObjects: firstObjects,
      boosterObjects: secondObjects,
      onlyInOriginal,
      onlyInBooster,
      commonObjects,
    });
  }

  const functionsMatch = matchingCount === allFunctionNames.size;
  const bucketsMatch = matchingBucketCount === allBucketNames.size;

  return {
    totalFunctions: allFunctionNames.size,
    matchingFunctions: matchingCount,
    mismatchingFunctions: allFunctionNames.size - matchingCount,
    functions: functionComparisons,
    totalBuckets: allBucketNames.size,
    matchingBuckets: matchingBucketCount,
    mismatchingBuckets: allBucketNames.size - matchingBucketCount,
    buckets: bucketComparisons,
    overallMatch: functionsMatch && bucketsMatch,
  };
}

/**
 * Print comparison results to console
 */
function printResults(
  results: ComparisonResults,
  firstFile: string,
  secondFile: string,
): void {
  console.log('\n=== CDK States Comparison Results ===\n');

  console.log(`Comparing:`);
  console.log(`  First:  ${firstFile}`);
  console.log(`  Second: ${secondFile}\n`);

  console.log(`Total functions: ${results.totalFunctions}`);
  console.log(`Matching functions: ${results.matchingFunctions}`);
  console.log(`Mismatching functions: ${results.mismatchingFunctions}`);
  console.log(`Overall match: ${results.overallMatch ? 'YES' : 'NO'}\n`);

  // Print details for each function
  for (const func of results.functions) {
    const status = func.matches ? '✅ MATCH' : '❌ MISMATCH';
    const filesStatus = func.filesMatch ? '✅' : '❌';
    const executionStatus = func.executionMatch ? '✅' : '❌';

    console.log(`${status} ${func.functionName}`);
    console.log(`  Files ${filesStatus} | Execution ${executionStatus}`);
    console.log(
      `  First total: ${func.originalFiles.length}, Second total: ${func.boosterFiles.length}, Common: ${func.commonFiles.length}`,
    );

    // Show execution comparison details
    console.log(`  Execution: ${func.executionComparison.details}`);

    // Always show file-by-file comparison for better visibility
    if (func.fileDetails.length > 0) {
      console.log('  File-by-file comparison:');
      func.fileDetails.forEach((file) => {
        let fileStatus = '';
        switch (file.status) {
          case 'match':
            fileStatus = '    ✅';
            break;
          case 'only-in-first':
            fileStatus = '    ❌ (only in first)';
            break;
          case 'only-in-second':
            fileStatus = '    ➕ (only in second)';
            break;
        }
        console.log(`${fileStatus} ${file.fileName}`);
      });
    } else {
      console.log('  No files found in either deployment');
    }

    console.log('');
  }

  // Print S3 bucket comparison
  if (results.buckets.length > 0) {
    console.log('\n=== S3 Bucket Comparison ===\n');
    console.log(`Total buckets: ${results.totalBuckets}`);
    console.log(`Matching buckets: ${results.matchingBuckets}`);
    console.log(`Mismatching buckets: ${results.mismatchingBuckets}\n`);

    for (const bucket of results.buckets) {
      const status = bucket.matches ? '✅ MATCH' : '❌ MISMATCH';
      console.log(`${status} ${bucket.bucketName}`);
      console.log(
        `  First total: ${bucket.originalObjects.length}, Second total: ${bucket.boosterObjects.length}, Common: ${bucket.commonObjects.length}`,
      );

      if (bucket.onlyInOriginal.length > 0) {
        console.log('  Only in first:');
        bucket.onlyInOriginal.forEach((o) => console.log(`    ❌ ${o}`));
      }
      if (bucket.onlyInBooster.length > 0) {
        console.log('  Only in second:');
        bucket.onlyInBooster.forEach((o) => console.log(`    ➕ ${o}`));
      }
      if (bucket.commonObjects.length > 0) {
        console.log('  Common objects:');
        bucket.commonObjects.forEach((o) => console.log(`    ✅ ${o}`));
      }
      console.log('');
    }
  }

  // Final summary
  if (results.overallMatch) {
    console.log(
      '🎉 All Lambda functions and S3 buckets have identical structures!',
    );
  } else {
    console.log(
      '⚠️  Some Lambda functions or S3 buckets have different structures.',
    );
    console.log(
      `Functions matching: ${results.matchingFunctions}/${results.totalFunctions}`,
    );
    console.log(
      `Executions matching: ${results.functions.filter((f) => f.executionMatch).length}/${results.totalFunctions}`,
    );
    if (results.totalBuckets > 0) {
      console.log(
        `Buckets matching: ${results.matchingBuckets}/${results.totalBuckets}`,
      );
    }
  }
}

/**
 * Main execution function
 */
async function main() {
  const args = process.argv.slice(2);

  if (args.length !== 2) {
    console.error(
      'Usage: npx tsx compare-states.ts <first-file.json> <second-file.json>',
    );
    console.error('');
    console.error('Examples:');
    console.error(
      '  npx tsx compare-states.ts cdk-original-function-files.json cdk-booster-function-files.json',
    );
    console.error('  npx tsx compare-states.ts ./original.json ./booster.json');
    process.exit(1);
  }

  const [firstFile, secondFile] = args;
  const firstFilePath = path.resolve(firstFile);
  const secondFilePath = path.resolve(secondFile);

  try {
    const results = compareCdkStates(firstFilePath, secondFilePath);
    printResults(results, firstFile, secondFile);

    // Exit with error code if there are mismatches
    process.exit(results.overallMatch ? 0 : 1);
  } catch (error) {
    console.error('Error comparing CDK states:', error);
    process.exit(1);
  }
}

// Execute main function only when script is run directly
main().catch(console.error);

export {
  compareCdkStates,
  ComparisonResults,
  FunctionComparison,
  FileComparison,
  ExecutionComparison,
  BucketComparison,
};
