/**
 * Lambda Function State Export Script
 *
 * This script exports the state of AWS Lambda functions deployed via CDK by reading CDK outputs,
 * downloading function code from AWS, and listing all files contained in each function.
 *
 * PURPOSE:
 * - Reads CDK outputs JSON file to extract Lambda function names
 * - Connects to AWS Lambda service to retrieve function code
 * - Downloads and extracts ZIP files containing function code
 * - Lists all files within each Lambda function package
 * - Generates a comprehensive report of all function contents
 *
 * USAGE:
 *   npx tsx scripts/export-state.ts <input-cdk-outputs.json> <output-file.json>
 *   or
 *   node dist/scripts/export-state.js <input-cdk-outputs.json> <output-file.json>
 *
 * PARAMETERS:
 *   input-cdk-outputs.json : Path to the CDK outputs JSON file (generated by 'cdk deploy')
 *   output-file.json       : Path where the analysis results will be written
 *
 * EXAMPLES:
 *   npx tsx ../../scripts/export-state.ts cdk-outputs.json cdk-original-function-files.json
 *
 * PREREQUISITES:
 * - AWS credentials configured (via AWS CLI, environment variables, or IAM roles)
 * - Lambda functions must be accessible with current AWS credentials
 * - Required permissions: lambda:GetFunction
 *
 * OUTPUT FORMAT:
 * The script generates a JSON file with the following structure:
 * {
 *   "functions": [
 *     {
 *       "functionName": "my-function-name",
 *       "files": ["index.js", "package.json", "node_modules/..."]
 *     }
 *   ],
 *   "timestamp": "2023-12-07T10:30:00.000Z"
 * }
 *
 * ERROR HANDLING:
 * - Individual function errors are captured and included in the output
 * - Script continues processing other functions if one fails
 * - Creates output directory if it doesn't exist
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  LambdaClient,
  GetFunctionCommand,
  GetFunctionResponse,
} from '@aws-sdk/client-lambda';
import AdmZip from 'adm-zip';

/**
 * Interface representing the structure of CDK outputs JSON file
 * Each stack contains multiple outputs with key-value pairs
 */
interface CdkOutputs {
  [stackName: string]: {
    [outputName: string]: string;
  };
}

/**
 * Interface representing the file list for a single Lambda function
 */
interface FunctionFilesList {
  functionName: string; // AWS Lambda function name
  files: string[]; // Array of file paths within the function package
}

/**
 * Interface representing the complete results output
 */
interface Results {
  functions: FunctionFilesList[]; // Array of all processed functions
  timestamp: string; // ISO timestamp when the analysis was performed
}

/**
 * Main function that reads CDK outputs, extracts Lambda function names,
 * downloads function code from AWS, and lists all files in each function
 *
 * @param inputFile - Path to the CDK outputs JSON file
 * @param outputFile - Path where the results will be written
 */
async function exportLambdaState(
  inputFile: string,
  outputFile: string,
): Promise<void> {
  try {
    // Read the CDK outputs file and parse JSON content
    const outputsContent = fs.readFileSync(inputFile, 'utf-8');
    const outputs: CdkOutputs = JSON.parse(outputsContent);

    // Extract Lambda function names from all stacks in the CDK outputs
    // Function names are identified by outputs containing 'FunctionName' in the key
    const functionNames: string[] = [];
    for (const stack of Object.values(outputs)) {
      for (const [key, value] of Object.entries(stack)) {
        if (key.includes('FunctionName')) {
          functionNames.push(value);
        }
      }
    }

    // Sort function names alphabetically for consistent processing order
    functionNames.sort();

    console.log(`Found ${functionNames.length} Lambda functions`);

    // Initialize AWS Lambda client with default configuration
    // Uses AWS credentials from environment or AWS CLI configuration
    const lambdaClient = new LambdaClient({});

    // Initialize results object with metadata
    const results: Results = {
      functions: [],
      timestamp: new Date().toISOString(),
    };

    // Track if any errors occurred during processing
    let hasErrors = false;

    // Process each Lambda function to get its file listing
    for (const functionName of functionNames) {
      console.log(`Processing function: ${functionName}`);

      try {
        // Create AWS Lambda GetFunction command to retrieve function metadata and code location
        const command = new GetFunctionCommand({
          FunctionName: functionName,
        });

        // Execute the command to get function details
        const response: GetFunctionResponse = await lambdaClient.send(command);

        // Check if the function has code and a download location
        if (response.Code?.Location) {
          // Download the function code ZIP file from the presigned URL
          const codeResponse = await fetch(response.Code.Location);
          const codeBuffer = Buffer.from(await codeResponse.arrayBuffer());

          // Extract and analyze the ZIP file contents
          const zip = new AdmZip(codeBuffer);
          const zipEntries = zip.getEntries();

          // Get list of all files (excluding directories) and sort them
          const files = zipEntries
            .filter((entry) => !entry.isDirectory) // Only include files, not directories
            .map((entry) => entry.entryName) // Extract file paths
            .sort(); // Sort alphabetically for consistent output

          // Add the function's file list to results
          results.functions.push({
            functionName,
            files,
          });

          console.log(`  Found ${files.length} files`);
        }
      } catch (error) {
        // Handle errors for individual functions and mark as error
        hasErrors = true;
        console.error(`Error processing function ${functionName}:`, error);
        results.functions.push({
          functionName,
          files: [
            `Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
          ],
        });
      }
    }

    // Extract output directory path from the output file path
    const outputDir = path.dirname(outputFile);

    // Ensure output directory exists before writing the results file
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Sort functions by name before writing to output for consistent results
    results.functions.sort((a, b) =>
      a.functionName.localeCompare(b.functionName),
    );

    // Write the complete results to the specified output file with pretty formatting
    fs.writeFileSync(outputFile, JSON.stringify(results, null, 2));
    console.log(`Results written to: ${outputFile}`);

    // Exit with error code if any function processing failed
    if (hasErrors) {
      console.error(
        'Some functions failed to process. Exiting with error code.',
      );
      process.exit(1);
    }
  } catch (error) {
    // Handle any top-level errors and exit with error code
    console.error('Error:', error);
    process.exit(1);
  }
}

/**
 * Main execution function that handles command line arguments and validation
 */
async function main() {
  // Extract command line arguments (excluding node and script path)
  const args = process.argv.slice(2);

  // Validate that exactly two arguments are provided
  if (args.length !== 2) {
    console.error(
      'Usage: npx tsx export-state.ts <input-cdk-outputs.json> <output-file.json>',
    );
    process.exit(1);
  }

  const [inputFile, outputFile] = args;

  // Verify that the input file exists before proceeding
  if (!fs.existsSync(inputFile)) {
    console.error(`Input file not found: ${inputFile}`);
    process.exit(1);
  }

  // Execute the main function
  await exportLambdaState(inputFile, outputFile);
}

// Execute main function only when script is run directly (not when imported)
main().catch(console.error);

// Export the main function for potential programmatic use
export { exportLambdaState };
