/**
 * Lambda Function State Export Script
 *
 * This script exports the state of AWS Lambda functions deployed via CDK by reading CDK outputs,
 * downloading function code from AWS, and listing all files contained in each function.
 *
 * PURPOSE:
 * - Reads CDK outputs JSON file to extract Lambda function names
 * - Connects to AWS Lambda service to retrieve function code
 * - Downloads and extracts ZIP files containing function code
 * - Lists all files within each Lambda function package
 * - Generates a comprehensive report of all function contents
 *
 * USAGE:
 *   npx tsx scripts/export-state.ts <input-cdk-outputs.json> <output-file.json>
 *   or
 *   node dist/scripts/export-state.js <input-cdk-outputs.json> <output-file.json>
 *
 * PARAMETERS:
 *   input-cdk-outputs.json : Path to the CDK outputs JSON file (generated by 'cdk deploy')
 *   output-file.json       : Path where the analysis results will be written
 *
 * EXAMPLES:
 *   npx tsx ../../scripts/export-state.ts cdk-outputs.json cdk-original-function-files.json
 *
 * PREREQUISITES:
 * - AWS credentials configured (via AWS CLI, environment variables, or IAM roles)
 * - Lambda functions must be accessible with current AWS credentials
 * - Required permissions: lambda:GetFunction
 *
 * OUTPUT FORMAT:
 * The script generates a JSON file with the following structure:
 * {
 *   "functions": [
 *     {
 *       "functionName": "my-function-name",
 *       "files": ["index.js", "package.json", "node_modules/..."]
 *     }
 *   ],
 *   "timestamp": "2023-12-07T10:30:00.000Z"
 * }
 *
 * ERROR HANDLING:
 * - Individual function errors are captured and included in the output
 * - Script continues processing other functions if one fails
 * - Creates output directory if it doesn't exist
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  LambdaClient,
  GetFunctionCommand,
  GetFunctionResponse,
  InvokeCommand,
} from '@aws-sdk/client-lambda';
import {
  S3Client,
  ListObjectsV2Command,
  GetObjectCommand,
} from '@aws-sdk/client-s3';
import AdmZip from 'adm-zip';

/**
 * Interface representing the structure of CDK outputs JSON file
 * Each stack contains multiple outputs with key-value pairs
 */
interface CdkOutputs {
  [stackName: string]: {
    [outputName: string]: string;
  };
}

/**
 * Interface representing the execution result for a Lambda function
 */
interface FunctionExecutionResult {
  success: boolean;
  output?: string;
  error?: string;
  statusCode?: number;
  executedPayload?: any;
}

/**
 * Interface representing the file list for a single Lambda function
 */
interface FunctionFilesList {
  functionName: string; // AWS Lambda function name
  files: string[]; // Array of file paths within the function package
  execution: FunctionExecutionResult; // Execution result
}

/**
 * Interface representing the state of an S3 bucket deployed via BucketDeployment
 */
interface BucketState {
  bucketName: string;
  objects: string[];
  markerContent?: string;
}

/**
 * Interface representing the complete results output
 */
interface Results {
  functions: FunctionFilesList[];
  buckets: BucketState[];
  timestamp: string;
}

/**
 * Main function that reads CDK outputs, extracts Lambda function names,
 * downloads function code from AWS, and lists all files in each function
 *
 * @param inputFile - Path to the CDK outputs JSON file
 * @param outputFile - Path where the results will be written
 */
async function exportLambdaState(
  inputFile: string,
  outputFile: string,
): Promise<void> {
  try {
    // Read the CDK outputs file and parse JSON content
    const outputsContent = fs.readFileSync(inputFile, 'utf-8');
    const outputs: CdkOutputs = JSON.parse(outputsContent);

    // Extract Lambda function names from all stacks in the CDK outputs
    // Function names are identified by outputs containing 'FunctionName' in the key
    const functionNames: string[] = [];
    for (const stack of Object.values(outputs)) {
      for (const [key, value] of Object.entries(stack)) {
        if (key.includes('FunctionName')) {
          functionNames.push(value);
        }
      }
    }

    // Sort function names alphabetically for consistent processing order
    functionNames.sort();

    console.log(`Found ${functionNames.length} Lambda functions`);

    // Initialize AWS Lambda client with default configuration
    // Uses AWS credentials from environment or AWS CLI configuration
    const lambdaClient = new LambdaClient({});

    // Initialize results object with metadata
    const results: Results = {
      functions: [],
      buckets: [],
      timestamp: new Date().toISOString(),
    };

    // Track if any errors occurred during processing
    let hasErrors = false;

    // Process each Lambda function to get its file listing
    for (const functionName of functionNames) {
      console.log(`Processing function: ${functionName}`);

      try {
        // Create AWS Lambda GetFunction command to retrieve function metadata and code location
        const command = new GetFunctionCommand({
          FunctionName: functionName,
        });

        // Execute the command to get function details
        const response: GetFunctionResponse = await lambdaClient.send(command);

        let files: string[] = [];

        // Check if the function has code and a download location
        if (response.Code?.Location) {
          // Download the function code ZIP file from the presigned URL
          const codeResponse = await fetch(response.Code.Location);
          const codeBuffer = Buffer.from(await codeResponse.arrayBuffer());

          // Extract and analyze the ZIP file contents
          const zip = new AdmZip(codeBuffer);
          const zipEntries = zip.getEntries();

          // Get list of all files (excluding directories) and sort them
          files = zipEntries
            .filter((entry) => !entry.isDirectory) // Only include files, not directories
            .map((entry) => entry.entryName) // Extract file paths
            .sort(); // Sort alphabetically for consistent output

          console.log(`  Found ${files.length} files`);
        }

        // Execute the Lambda function to capture its output
        console.log(`  Executing function: ${functionName}`);
        const executionResult = await executeLambdaFunction(
          lambdaClient,
          functionName,
        );

        if (executionResult.success) {
          console.log(`  ✅ Function executed successfully`);
        } else {
          hasErrors = true;
          console.log(
            `  ❌ Function execution failed: ${executionResult.error}`,
          );
        }

        // Add the function's file list and execution result to results
        results.functions.push({
          functionName,
          files,
          execution: executionResult,
        });
      } catch (error) {
        // Handle errors for individual functions and mark as error
        hasErrors = true;
        console.error(`Error processing function ${functionName}:`, error);
        results.functions.push({
          functionName,
          files: [
            `Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
          ],
          execution: {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error',
          },
        });
      }
    }

    // Export S3 bucket state for BucketDeployment verification
    const bucketNames: string[] = [];
    for (const stack of Object.values(outputs)) {
      for (const [key, value] of Object.entries(stack)) {
        if (key.includes('BucketDeploymentBucketName')) {
          bucketNames.push(value);
        }
      }
    }
    bucketNames.sort();

    if (bucketNames.length > 0) {
      console.log(`\nFound ${bucketNames.length} BucketDeployment bucket(s)`);
      const s3Client = new S3Client({});

      for (const bucketName of bucketNames) {
        console.log(`Processing bucket: ${bucketName}`);
        try {
          const bucketState = await exportBucketState(s3Client, bucketName);
          results.buckets.push(bucketState);
          console.log(`  Found ${bucketState.objects.length} objects`);
          if (bucketState.markerContent) {
            console.log(`  Marker: ${bucketState.markerContent}`);
          }
        } catch (error) {
          hasErrors = true;
          console.error(`Error processing bucket ${bucketName}:`, error);
          results.buckets.push({
            bucketName,
            objects: [
              `Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
            ],
          });
        }
      }
    }

    // Extract output directory path from the output file path
    const outputDir = path.dirname(outputFile);

    // Ensure output directory exists before writing the results file
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Sort functions and buckets by name before writing for consistent results
    results.functions.sort((a, b) =>
      a.functionName.localeCompare(b.functionName),
    );
    results.buckets.sort((a, b) => a.bucketName.localeCompare(b.bucketName));

    // Write the complete results to the specified output file with pretty formatting
    fs.writeFileSync(outputFile, JSON.stringify(results, null, 2));
    console.log(`Results written to: ${outputFile}`);

    // Exit with error code if any function processing failed
    if (hasErrors) {
      console.error(
        'Some functions failed to process. Exiting with error code.',
      );
      process.exit(1);
    }
  } catch (error) {
    // Handle any top-level errors and exit with error code
    console.error('Error:', error);
    process.exit(1);
  }
}

/**
 * Execute a Lambda function with a test payload
 */
async function executeLambdaFunction(
  lambdaClient: LambdaClient,
  functionName: string,
): Promise<FunctionExecutionResult> {
  try {
    // Default test payload - can be customized based on function requirements
    const testPayload = {
      test: true,
      timestamp: new Date().toISOString(),
      source: 'cdk-booster-state-export',
    };

    const invokeCommand = new InvokeCommand({
      FunctionName: functionName,
      Payload: JSON.stringify(testPayload),
      InvocationType: 'RequestResponse', // Synchronous invocation
    });

    const response = await lambdaClient.send(invokeCommand);

    // Decode the response payload
    const payload = response.Payload
      ? new TextDecoder().decode(response.Payload)
      : '';

    return {
      success: !response.FunctionError,
      output: payload,
      statusCode: response.StatusCode,
      executedPayload: testPayload,
      error: response.FunctionError || undefined,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown execution error',
      executedPayload: {
        test: true,
        timestamp: new Date().toISOString(),
        source: 'cdk-booster-state-export',
      },
    };
  }
}

/**
 * Export the state of an S3 bucket: list all object keys and read the deploy marker
 */
async function exportBucketState(
  s3Client: S3Client,
  bucketName: string,
): Promise<BucketState> {
  const objects: string[] = [];
  let continuationToken: string | undefined;

  do {
    const listResponse = await s3Client.send(
      new ListObjectsV2Command({
        Bucket: bucketName,
        ContinuationToken: continuationToken,
      }),
    );

    if (listResponse.Contents) {
      for (const obj of listResponse.Contents) {
        if (obj.Key) {
          objects.push(obj.Key);
        }
      }
    }

    continuationToken = listResponse.NextContinuationToken;
  } while (continuationToken);

  objects.sort();

  let markerContent: string | undefined;
  try {
    const markerResponse = await s3Client.send(
      new GetObjectCommand({
        Bucket: bucketName,
        Key: 'deploy-marker.txt',
      }),
    );
    markerContent = await markerResponse.Body?.transformToString('utf-8');
  } catch {
    // deploy-marker.txt may not exist
  }

  return { bucketName, objects, markerContent };
}

/**
 * Main execution function that handles command line arguments and validation
 */
async function main() {
  // Extract command line arguments (excluding node and script path)
  const args = process.argv.slice(2);

  // Validate that exactly two arguments are provided
  if (args.length !== 2) {
    console.error(
      'Usage: npx tsx export-state.ts <input-cdk-outputs.json> <output-file.json>',
    );
    process.exit(1);
  }

  const [inputFile, outputFile] = args;

  // Verify that the input file exists before proceeding
  if (!fs.existsSync(inputFile)) {
    console.error(`Input file not found: ${inputFile}`);
    process.exit(1);
  }

  // Execute the main function
  await exportLambdaState(inputFile, outputFile);
}

// Execute main function only when script is run directly (not when imported)
main().catch(console.error);

// Export the main function for potential programmatic use
export { exportLambdaState };
